<a href="https://colab.research.google.com/github/kmk0909/2026-BDA/blob/main/code/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 패키지 numpy 개요와 자료형 ndarray

In [ ]:
import numpy as np
a= np.ndarray((2, 3))
a

array([[3.07299992e-315, 0.00000000e+000, 6.65798032e-310],
       [6.65800638e-310, 6.65798060e-310, 6.65798060e-310]])

In [ ]:
import numpy as np
a= np.ndarray((3, 2), dtype=int)
a

array([[          626338259,                   0],
       [ 320318678115549184, 7173110024487108609],
       [ 105553498576781431, 2338053341824774656]])

In [ ]:
a= np.ndarray((3, 2), int)
a

array([[         626338397,                  0],
       [                 0,  25051277296795684],
       [249950291654082960,           24576089]])

In [ ]:
import numpy as np
a = np.array([1, 2, 3], dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


### 내장함수 arange()와 linspace()

In [1]:
import numpy as np

print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,7,2))

[0 1 2]
[3 4 5 6]
[3 5]


In [2]:
print(np.arange(2.0))
print(np.arange(2.0,6.5))
print(np.arange(2.0,6.5,0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [ ]:
import numpy as np
a= np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [3]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a[6]

np.int64(36)

In [ ]:
int(a[6])

36

In [ ]:
a[-2]

np.int64(64)

In [ ]:
a[1:4]

array([1, 4, 9])

In [ ]:
a[-5:-1]

array([25, 36, 49, 64])

In [ ]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[8:2:-2]

array([64, 36, 16])

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a.reshape(3, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[:, 1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
a[1, :]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:, 1,1]

array([ 5, 17])

In [ ]:
a[:, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[1:]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[:]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[:, :, 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[..., 1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
a[1, ...,1]

array([13, 17, 21])

In [ ]:
a[1, :, 1]

array([13, 17, 21])

In [ ]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.linspace(2.0, 3.0 )

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 np.float64(0.02040816326530612))

In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)


(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 np.float64(0.02))

In [ ]:
print((3-2)/ 50)

0.02


In [ ]:
np.linspace(2.0, 3.0,num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25))

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), np.float64(0.2))

###내장함수 zeros()와 ones(),empty()

In [ ]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [ ]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full((2, 3), (1,2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full((3,4), range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full((4, 3), fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.empty([2, 2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty([2, 3], dtype=int)

array([[      621982109,               0, 134759021847184],
       [134759549290320, 134759027573376, 134759027609904]])

###배열 연산

In [ ]:
import numpy as np
a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b= np.full_like(a, [1,2,3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5, 4, 1)

b

array([0.5, 1.5, 2.5, 3.5])

In [ ]:
a @ b

np.float64(17.0)

In [ ]:
a.dot(b)

np.float64(17.0)

In [ ]:
a = np.array([[10,20], [5, 8], [1,2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum()

np.int64(46)

In [ ]:
a.sum(axis=0)

array([16, 30])

In [ ]:
a.sum(axis=1)

array([30, 13,  3])

In [ ]:
import numpy as np

print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [ ]:
a = np.array([[3, 5, 8], [1,2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [ ]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [ ]:
import numpy as np
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [ ]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [ ]:
np.add(a, b)

array([ 3,  6, 11])

In [ ]:
np.divide(a, b)

array([0.5, 2. , 4.5])

In [ ]:
np.power(a, b)

array([ 1, 16, 81])

###배열 슬라이싱과 형태 수정

In [ ]:
import numpy as np
a = np.power(np.arange(10), 2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
print(a[3])
print(a[-2])

9
64


In [ ]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [ ]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [ ]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a[2:5] - [-5, -5, -5]
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [ ]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [ ]:
a[-2 :]

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
a[-2, ]

array([18, 19, 20, 21, 22, 23])

In [ ]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [ ]:
a[:, 1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [ ]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [ ]:
a[..., 1]

array([ 1,  7, 13, 19, 25])

In [ ]:
a[1, ...,1]

array(7)

In [ ]:
a[0, ...]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [ ]:
y = np.swapaxes(x, 0, 1)
y

array([[7],
       [8],
       [9]])

In [ ]:
y = np.swapaxes(x, 1, 0)
y

array([[7],
       [8],
       [9]])

In [ ]:
y[0, 0] = 10
x

array([[10,  8,  9]])

In [ ]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [ ]:
np.transpose(x, (2, 0, 1))

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [ ]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [ ]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [ ]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [ ]:
org

array([  0,   1, 200,   3,   4])

In [ ]:
c = org.copy()
c

array([  0,   1, 200,   3,   4])

In [ ]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
y = x.reshape(2,3)
y

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y.base

array([0, 1, 2, 3, 4, 5])

In [ ]:
z = y.transpose()
z.base

array([0, 1, 2, 3, 4, 5])

In [ ]:
c = z.copy()
print(c.base)

None


In [ ]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [ ]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[3:5]= [30,40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

###브로드캐스팅

In [ ]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [ ]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [ ]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y = arange(3, 10, 3).reshape(3,1)
y

array([[3],
       [6],
       [9]])

In [ ]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [ ]:
from numpy import arange
x = arange(1, 4)
x

array([1, 2, 3])

In [ ]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [ ]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
x/y

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [ ]:
from numpy import arange
x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [ ]:
y = arange(1, 3)
y

array([1, 2])

In [ ]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [ ]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [ ]:
np.newaxis is None

True

In [ ]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [ ]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

#고급 색인

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[1]

np.int64(1)

In [ ]:
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
x[[1]]

array([1])

In [ ]:
x[[1, 1, 2, 5]]

array([1, 1, 2, 5])

In [ ]:
x[[1, 1, 2, 5, -1, -2, -5]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
x = np.arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[5]

array([40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
x[[6, 5]]

array([[48, 49, 50, 51, 52, 53, 54, 55],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[[0, 1]]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
x[0, 1]

np.int64(1)

In [ ]:
x[ [0], [1] ]

array([1])

In [ ]:
x[ [0, 1] ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
x[:, [1] ]

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49]])

In [ ]:
x[:, [2, 1] ]

array([[ 2,  1],
       [10,  9],
       [18, 17],
       [26, 25],
       [34, 33],
       [42, 41],
       [50, 49]])

In [ ]:
x[ [1,3] ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x[ [1,3], : ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
x [ [1], [2] ]

array([10])

In [ ]:
x[ [ 1,3], [2,2] ]

array([10, 26])

In [ ]:
x[ [ 1,3], [2] ]

array([10, 26])

In [ ]:
x[ [ 1,3], 2 ]

array([10, 26])

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[ [0, 2, 4], 1 ]

array([ 1, 17, 33])

In [ ]:
x[ [0, 2, 4], :2 ]

array([[ 0,  1],
       [16, 17],
       [32, 33]])

In [ ]:
x[ [0, 2, 4], 2 ]

array([ 2, 18, 34])

In [ ]:
x[ [0, 2, 4], [0, 1, 2] ]

array([ 0, 17, 34])

In [ ]:
a = np.arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ [2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[[2, 3]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
np.arange(2, 4)

array([2, 3])

In [ ]:
a[np.arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [ ]:
a[ np.arange(2, 4)][ :, [1, 0] ]

array([[17, 16],
       [25, 24]])

In [ ]:
a[ np.arange(2, 5) ]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[ np.arange(2, 5) ][:, [1, 0 , 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
np.arange(-1, -8, -1)

array([-1, -2, -3, -4, -5, -6, -7])

In [ ]:
a[ np.arange(2, 5) ][:, np.arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [ ]:
from numpy import arange

x = arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [ ]:
x[np.array([0, 2, 4]), 1]

array([ 1, 17, 33])

In [ ]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


In [ ]:
from numpy import arange

a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [ ]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [ ]:
a[arange(2, 5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])