<a href="https://colab.research.google.com/github/kmk0909/2026-BDA/blob/main/code/04w_array_stack_split_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###4.1 배열 결합

In [ ]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
c = np.arange(1, 6, 2)
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [ ]:
c[:, None]

array([[1],
       [3],
       [5]])

In [ ]:
c[:, np.newaxis ]

array([[1],
       [3],
       [5]])

In [ ]:
cc = np.expand_dims(c, axis =1)
cc

array([[1],
       [3],
       [5]])

In [ ]:
np.hstack( (a, cc) )

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, cc))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
np.c_[a, b], np.c_[ (a, b) ]

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.c_[a, b], np.column_stack((a, b))

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.column_stack((x, y))


array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
import numpy as np
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b = np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack( (a,b) )

/tmp/ipykernel_9500/266430481.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack( (a,b) )


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
import numpy as np
a = np.array([1,2])
b = np.array([3,4])
c= np.array([5,6])
np.concatenate((a, b, c))


array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate( (x, y) )

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate( (x, y), axis = 1 )

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate( (x, y, z), axis = 1 )

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate( (x, y, z), axis = None )

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23])

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [ ]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a, b), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np
np.arange(1, 19).reshape(3, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
np.arange(16).reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
x = np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 26).reshape(2, 3)

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [ ]:
ax0.shape

(3, 2, 3)

In [ ]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [ ]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
ax2.shape

(2, 3, 3)

In [ ]:
print("np.stack((x, y , z), axis=0)")
print(np.stack((x, y , z), axis=0))
print("np.stack((x, y , z), axis=1)")
print(np.stack((x, y , z), axis=1))
print("np.stack((x, y , z), axis=2)")
print(np.stack((x, y , z), axis=2))

np.stack((x, y , z), axis=0)
[[[ 0  1  2]
  [ 3  4  5]]

 [[10 11 12]
  [13 14 15]]

 [[20 21 22]
  [23 24 25]]]
np.stack((x, y , z), axis=1)
[[[ 0  1  2]
  [10 11 12]
  [20 21 22]]

 [[ 3  4  5]
  [13 14 15]
  [23 24 25]]]
np.stack((x, y , z), axis=2)
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]]

 [[ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]]]


In [ ]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
z[:, :, np.newaxis]

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.expand_dims(y, axis=2)

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
import numpy as np

a = np.arange(1,13).reshape(3,4)
c = np.arange(1, 6, 2)
a, c

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 3, 5]))

In [ ]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack( (a, c) )

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(1, 5)
a, b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([1, 2, 3, 4]))

In [ ]:
np.row_stack((a, b))

/tmp/ipykernel_2228/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.c_[a, b]
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.r_['-1,2,0', a, b]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [4]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [7]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [8]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [9]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [10]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [11]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [12]:
np.row_stack((a, b))

/tmp/ipykernel_11986/2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [15]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [16]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [17]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [23]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [25]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [26]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [27]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

##4.2 배열 분리


In [ ]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a = np.arange(1,4)
b = np.arange(4,7)
a, b

(array([1, 2, 3]), array([4, 5, 6]))

In [ ]:
x = np.arange(1,7).reshape(2, 3)
y = np.arange(7, 13).reshape(2, 3)
x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [ ]:
np.vstack((a, b)) # 1D -->2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a, b)) # 1D -->2D

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack((x, y)) # 2D -->2D

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((x, y)) # 2D -->2D

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
np.column_stack((a, b))# 1D -->2D

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a, b)), np.c_[a, b] # 1D -->2D

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [ ]:
np.column_stack((x, y)), np.c_[x, y] # 1D -->2D

(array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [ ]:
m = np.arange(24).reshape(2, 3, 4)
m

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
n = np.arange(96).reshape(4, 4, 6)
n

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]],

       [[72, 73, 74, 75, 76, 77],
        [78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95]]])

In [ ]:
np.split(n, 2)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]]]),
 array([[[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83],
         [84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]

In [ ]:
np.split(n, 2)[1].shape

(2, 4, 6)

In [ ]:
np.split(n, 2, axis=1)

[array([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],
 
        [[24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]],
 
        [[48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59]],
 
        [[72, 73, 74, 75, 76, 77],
         [78, 79, 80, 81, 82, 83]]]),
 array([[[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]],
 
        [[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47]],
 
        [[60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]],
 
        [[84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95]]])]

In [ ]:
np.split(n, 2, axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8],
         [12, 13, 14],
         [18, 19, 20]],
 
        [[24, 25, 26],
         [30, 31, 32],
         [36, 37, 38],
         [42, 43, 44]],
 
        [[48, 49, 50],
         [54, 55, 56],
         [60, 61, 62],
         [66, 67, 68]],
 
        [[72, 73, 74],
         [78, 79, 80],
         [84, 85, 86],
         [90, 91, 92]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11],
         [15, 16, 17],
         [21, 22, 23]],
 
        [[27, 28, 29],
         [33, 34, 35],
         [39, 40, 41],
         [45, 46, 47]],
 
        [[51, 52, 53],
         [57, 58, 59],
         [63, 64, 65],
         [69, 70, 71]],
 
        [[75, 76, 77],
         [81, 82, 83],
         [87, 88, 89],
         [93, 94, 95]]])]

###난수 기초와 생성

In [ ]:
import numpy as np

rg = np.random.default_rng(1)
rg.random() # [0,1] 실수 난수


0.5118216247002567

In [ ]:
rg.random(4)

array([0.81962672, 0.68328691, 0.78709694, 0.19161626])

In [ ]:
rg.random( (3, 4, 2) )

array([[[0.80236416, 0.19132393],
        [0.08155262, 0.85522697],
        [0.8612835 , 0.8765371 ],
        [0.47190972, 0.27404839]],

       [[0.00709183, 0.6457209 ],
        [0.71990938, 0.83556922],
        [0.28187783, 0.21521817],
        [0.63933138, 0.80505483]],

       [[0.96367087, 0.15052483],
        [0.48221239, 0.89471586],
        [0.42271691, 0.58950206],
        [0.02449068, 0.67345989]]])

In [ ]:
import numpy as np

rg = np.random.default_rng(12)
rg.integers(1, 7, (3, 4) ) # [1,7] 정수 난수

array([[4, 2, 6, 6],
       [1, 2, 2, 2],
       [4, 3, 3, 2]])

In [ ]:
rg.integers(low=1, high=10, size=(2, 8)) #[1,10]

array([[9, 7, 6, 2, 2, 9, 3, 8],
       [8, 1, 5, 5, 5, 1, 7, 3]])

In [ ]:
import numpy as np

rg = np.random.default_rng(12)
rg.standard_normal(10) # 표준 정규 분포 실수 난수


array([-0.00682678,  1.04614329,  0.74158842,  0.72395654,  1.61877622,
       -1.20555814, -0.62695547, -1.32066321, -0.10775251,  0.99876366])

In [ ]:
rg.standard_normal( (3, 4) )

array([[-0.49737204, -0.11477278, -0.60545201, -0.59433942],
       [-0.28337538, -0.72841773,  0.76632779, -1.59608633],
       [ 0.82356213, -0.62556647, -0.54593996, -1.35084714]])

In [ ]:
rg.standard_normal( (10, 5) )

array([[ 1.90703845,  1.087977  , -1.31052632,  1.09121389, -0.47771203],
       [-0.18046727, -1.03852347, -0.87263922, -0.43785731,  0.03843202],
       [-1.15872738, -0.11689814, -0.75696048, -0.57539687, -0.93214658],
       [-0.67271667,  1.55342136, -1.66277083, -1.36164705, -0.11698245],
       [-0.54694451, -1.09942254,  0.3564349 , -1.22028567, -0.05590138],
       [ 0.89833647,  0.51270482, -0.34055498, -0.04877312,  0.11923643],
       [ 0.54830906, -1.00670962,  1.21361455,  0.698826  ,  1.80943967],
       [ 0.7877311 ,  0.97388754, -3.00213038, -0.49515859,  1.8083498 ],
       [ 0.33131801, -0.50758027,  0.64191451,  0.03552979,  0.3479325 ],
       [-0.77296839,  0.47527617,  1.46623498,  0.18924444,  0.39185938]])